name: Shared Steps for Docs
description: Common steps for installing requirements for docs
inputs:
  message:
    description: 'A message to log'
    required: false
    default: 'Default message'
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Create a virtual environment
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install docs dependencies
      shell: bash
      run: |
        pip install -e .[docs]
