name: Shared Steps for Docs

runs:
  using: "composite"
  steps:
    - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Create a virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install docs dependencies
        run: |
          pip install -e .[docs]
