name: Test Notebook-based Documentation

on: 
  push:

jobs:
  getting_started:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run shared steps
        uses: ./.github/actions/shared-steps
      - name: Execute the notebooks
        run: |
          pytest --junitxml=report-notebooks-getting-started.xml -vvv --nbmake "./docs/getting-started"
      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: report-notebooks-getting-started.xml
          path: ./report-notebooks-getting-started.xml
  how_to_grid:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run shared steps
        uses: ./.github/actions/shared-steps
      - name: Execute the notebooks
        run: |
          pytest --junitxml=report-notebooks-how-to.xml -vvv --nbmake "./docs/how-to/grid"
      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: report-notebooks-how-to-grid.xml
          path: ./report-notebooks-how-to-grid.xml
  how_to_multi_index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run shared steps
        uses: ./.github/actions/shared-steps
      - name: Execute the notebooks
        run: |
          pytest --junitxml=report-notebooks-how-to.xml -vvv --nbmake "./docs/how-to/multi-index"
      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: report-notebooks-how-to-multi-index.xml
          path: ./report-notebooks-how-to-multi-index.xml
