name: docs
on: 
  push:
    branches: ["dev", "main"]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run shared steps
        uses: ./.github/actions/shared-steps
        with:
          message: 'Executing Getting Started'
      - name: Build the docs
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          destination_dir: ./latest
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        with:
          ref: gh-pages
      - name: Configure Git
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Redirect main URL to the latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        run: |
          if [ ! -e "index.html" ]; then
            echo "<html>\n\t<head>\n\t\t<meta http-equiv=\"refresh\" content=\"0; url=latest/\" />\n\t</head>\n</html>" > index.html
            git add index.html
            git commit -m "Redirect the main URL to the latest documentation"
          fi
      - name: Push changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
      - name: Deploy to GitHub Pages (Main)
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          destination_dir: ./main
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          ref: gh-pages
      - name: Configure Git
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Redirect main URL to the latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          if [ ! -e "stable" ]; then
            ln -s main stable
            git add stable
            git commit -m "Redirect the main docs to the stable documentation"
          fi          
      - name: Push changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
      - name: Check out repo
        uses: actions/checkout@v4
