# This workflow automates the execution of notebooks-based documentation
# for testing purposes. To allow for parallel processing,
# different locations of notebooks are executed separately.
name: nbmake

on: 
  push:

jobs:
  getting-started:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Execute Getting Started notebooks
        uses: ./.github/actions/nbmake
        with:
          dir: ./docs/getting-started
  how-to-grid:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Execute How-To (grid) notebooks
        uses: ./.github/actions/nbmake
        with:
          dir: ./docs/how-to/grid
  how-to-multi-index-set:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Execute How-To (multi-index-set) notebooks
        uses: ./.github/actions/nbmake
        with:
          dir: ./docs/how-to/multi-index-set
