name: Test Notebooks-based Documentation

on: 
  push:
  pull_request:
    branches: ["dev", "main"]
    types: [opened, synchronize, closed]

jobs:
  nbtest:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'synchronize' 
    steps:
      - uses: actions/checkout@v4
