name: Test Notebooks-based Documentation

on: 
  push:
  pull_request:
    branches: ["dev", "main"]

jobs:
  getting_started:
    if: github.event_name != 'push' || github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run shared steps
        uses: ./.github/actions/shared-steps
        with:
          message: 'Executing Getting Started'
      - name: Execute the notebooks
        run: |
          pytest --junitxml=report-notebooks-getting-started.xml -vvv --nbmake "./docs/getting-started"
      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: report-notebooks-getting-started.xml
          path: ./report-notebooks-getting-started.xml
  how_to:
    if: github.event_name != 'push' || github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run shared steps
        uses: ./.github/actions/shared-steps
        with:
          message: 'Executing How-To'
      - name: Execute the notebooks
        run: |
          pytest --junitxml=report-notebooks-getting-how-to.xml -vvv --nbmake "./docs/how-to"
      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: report-notebooks-how-to.xml
          path: ./report-notebooks-how-to.xml
