name: Documentation Preview

on: 
  pull_request:
    branches: ["dev"]

permissions:
  contents: write

jobs:
  docs_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Pandoc
        run: |
          sudo apt-get install -y pandoc
      - name: Create a virtual environment
        run: |
          python -m venv venv &&
          source venv/bin/activate
      - name: Install docs dependencies
        run: |
          pip install -e .[docs]
      - name: Build the docs
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          destination_dir: pr-preview/${{ github.event.number }}
  docs_preview_cleanup:
    if: github.event.action == "closed"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Remove preview
        run: |
          git rm -r pr-preview/${{ github.event.number }}
          git commit -m "Remove preview for PR #${{ github.event.number }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
