name: documentation

on: 
  pull_request:
    branches: ["dev", "main"]
  push:
    branches: ["dev", "main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Pandoc
        run: |
          sudo apt-get install -y pandoc
      - name: Create a virtual environment
        run: |
          python -m venv venv &&
          source venv/bin/activate
      - name: Install docs dependencies
        run: |
          pip install -e .[docs]
      - name: Build the docs
        run: |
          cd minterpy/docs && make html
