name: Run Test Suite

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Create a virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install docs dependencies
        run: |
          pip install -e .[dev]
      - name: Run Pytest
        run: |
          pytest --junitxml=report-pytest.xml -vvv
      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: report-pytest.xml
          path: ./report-pytest.xml
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Create a virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install docs dependencies
        run: |
          pip install -e .[dev]
      - name: Disable NUMBA for coverage tests
        run: |
          export NUMBA_DISABLE_JIT=1
      - name: Run Pytest
        run: |
          pytest --junitxml=report-coverage.xml -vvv
      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: report-coverage.xml
          path: ./report-coverage.xml
